# Generated by Django 5.0.7 on 2024-08-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Age',
        ),
        migrations.DeleteModel(
            name='BloodPressure',
        ),
        migrations.DeleteModel(
            name='DiabetesPedigreeFunction',
        ),
        migrations.DeleteModel(
            name='Glucose',
        ),
        migrations.DeleteModel(
            name='Height',
        ),
        migrations.DeleteModel(
            name='Insulin',
        ),
        migrations.DeleteModel(
            name='Pregnancies',
        ),
        migrations.DeleteModel(
            name='SkinThickness',
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
