# Generated by Django 5.0.7 on 2024-08-31 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, default=0)),
                ('bmi', models.FloatField(blank=True, default=0)),
                ('insulin', models.FloatField(blank=True, default=0)),
                ('glucose', models.FloatField(blank=True, default=0)),
                ('blood_pressure', models.FloatField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
